default_border pixel 1
default_floating_border pixel 1

gaps inner 16
gaps outer 8
smart_gaps off

set $bg_dark      #111318
set $bg_surface   #1b2028
set $border_focus #4c566a
set $border_mute  #2b313c
set $text_light   #ffffff
set $text_muted   #96a1b2
set $alert        #bf616a

client.focused          $border_focus   $bg_surface     $text_light     $border_focus   $border_focus
client.focused_inactive $border_mute    $bg_dark        $text_muted     $border_mute    $border_mute
client.unfocused        $border_mute    $bg_dark        $text_muted     $border_mute    $border_mute
client.urgent           $alert          $bg_dark        $text_light     $alert          $alert