exec_always dbus-update-activation-environment --systemd \
    WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE

exec_always ~/.config/sway/wallpaper.sh
exec_always sh -c "pkill waybar; sleep 0.2; waybar"

input * {
    tap enabled
    natural_scroll disabled
}